language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-28.0.0

    # The SDK version used to compile your project
    - android-28
    # Target version
    - android-24

    # Image for emulator
    - sys-img-armeabi-v7a-android-24


addons:
  apt:
    packages:
      - iproute2
      - docker-ce
      
sudo: required

env:
  - DOCKER_COMPOSE_VERSION=1.22.0

# Update docker-compose Emulator Management: Create, Start and Wait
before_script:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  - android list targets
  - cat $(which android-wait-for-emulator)
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test  -no-window &

script: ./.travis.sh
