language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-28.0.0
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-28
    # Target version
    - android-24

    # Image for emulator
    - sys-img-armeabi-v7a-google_apis-24

    - extra
    - add-on


addons:
  apt:
    packages:
      - iproute2
      - docker-ce
      
sudo: required

# Update docker-compose Emulator Management: Create, Start and Wait
before_script:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - export TEST_POOL_IP=$(ip -o addr show | grep -E "eth0.*inet " | grep -E -o  -e "[0-9]*(\.[0-9]*){3}" | head -1)
  - android list targets
  - ci/create-emulator.sh
  - ci/travis.sh
